version: '2.1'

services:
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
        volumes:
        - ./init.sql:/data/application/init.sql
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: secret
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

    users-golang:
        container_name: users-golang
        restart: on-failure 
        build:
            context: ./users
            dockerfile: dockerfile
        ports: 
            - 8000:8000
        volumes:
        - ./users:/go/src
        depends_on:
            db:
                condition: service_healthy
        links:
            - db
    
    movies-golang:
        container_name: movies-golang
        restart: on-failure
        build:
            context: ./movies
            dockerfile: dockerfile
        ports: 
            - 9000:9000
        volumes:
        - ./movies:/go/src
        depends_on:
            db:
                condition: service_healthy
        links:
            - db

